# Generated by Django 5.1.3 on 2026-07-06 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_urls', models.JSONField(default=list)),
                ('verdict', models.CharField(blank=True, max_length=300)),
                ('notes_json', models.JSONField(default=list)),
                ('fix', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=40)),
                ('query', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=600)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'query'], name='core_produc_platfor_94058a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=200)),
                ('style_pref', models.CharField(default='frocks', max_length=200)),
                ('budget', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('products_json', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
