# Generated by Django 5.1.3 on 2026-07-09 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('top', 'Top / Shirt / Blouse'), ('bottom', 'Bottom / Pants / Skirt'), ('dress', 'Dress / Frock'), ('outerwear', 'Jacket / Blazer / Coat'), ('footwear', 'Shoes / Sandals / Heels'), ('accessory', 'Jewellery / Belt / Bag'), ('ethnic', 'Ethnic / Saree / Kurta'), ('other', 'Other')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
